# Generated by Django 4.1.3 on 2022-11-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_post_time_alter_user_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.CharField(max_length=6),
        ),
    ]
